Using PER_JOB_HISTORY_DIR for APEL reporting (HTCONDOR-293)
htcondor/htcondor-ce pull request #443
Opened 2021-03-26 19:28 UTC by markcoatsworth

New clean pull request for these changes, including fixes from previous comments

2021-03-26 20:13 UTC, brianhlin requested changes
It looks like this commit accidentally stomps on changes related to #426. Also a few other suggestions.

2021-03-26 20:13 UTC, brianhlin commented on contrib/apelscripts/condor_batch_blah.sh
> +    blah_record=`TZ=GMT condor_q -job $file \
```suggestion
    blah_record=`TZ=GMT condor_q -job "$file" \
```

2021-03-26 20:13 UTC, brianhlin commented on contrib/apelscripts/condor_batch_blah.sh
> +    batch_record=`TZ=GMT condor_q -job $file \
```suggestion
    batch_record=`TZ=GMT condor_q -job "$file" \
```

2021-03-26 20:13 UTC, brianhlin commented on contrib/apelscripts/condor_batch_blah.sh
> +        -format ".%s_${BATCH_HOST}|" ProcId \
```suggestion
    -format "%s|" GlobalJobId \
```

This was changed in #426

2021-03-26 20:13 UTC, brianhlin commented on contrib/apelscripts/condor_batch_blah.sh
> +        -format ".%v_${BATCH_HOST}\" " ProcId \
```suggestion
        -format "\"lrmsID=%s\" " GlobalJobId \
```

The matching change from #426

2021-03-29 20:40 UTC, markcoatsworth commented
@brianhlin I just pushed an update which addresses all your previous comments. I also changed the Is-History-File-Valid check to look for a GlobalJobId instead of ClusterId since we're now using the former as the unique job identifier.

2021-03-29 20:45 UTC, brianhlin approved these changes
LGTM! Overriding unrelated osg-test failures

2021-03-29 20:45 UTC, merged