Add ce diagrams to README.md (INF-1118)
htcondor/htcondor-ce pull request #580
Opened 2023-08-14 18:52 UTC by rc-jacob

Logical diagrams based off those found in Brian Lin's office, all made with mermaid-js

2024-01-18 19:07 UTC, ColeBollig requested changes
Just some minor nitpicky changes. I can't speak for the full validity of the graph flows and will yield the accuracy of these graphs to @brianhlin

2024-01-18 22:23 UTC, rc-jacob commented on README.md
> +	D[(Log)] --> C
This seems like a better idea. I'll add this suggestion.

2024-03-06 17:03 UTC, brianhlin commented
We merged this into the new main branch in #595 so we don't need this particular PR anymore. @rc-jacob we were able to retain your specific commits, though!

2024-03-06 17:08 UTC, timtheisen commented
Superseded by #595

2024-03-06 17:08 UTC, closed without merging